Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    patience: 3
    save_best_only: True
    eval_interval_epochs: 1
    debug_mode: False

YouTubeNet_yelp18_m1:
    model: YouTubeNet
    dataset_id: yelp18_m1_002
    margin: 1
    metrics: ['Recall(k=20)', 'Recall(k=50)', 'NDCG(k=20)', 'NDCG(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: adam
    learning_rate: 1.e-3
    batch_size: 256
    num_negs: 200
    embedding_dim: 64
    output_dim: 64
    user_hidden_units: null
    user_hidden_activations: ReLU
    user_final_activation: null
    embedding_regularizer: 1.e-6
    net_regularizer: 0
    embedding_dropout: 0
    net_dropout: 0
    similarity_score: dot
    loss: SoftmaxCrossEntropyLoss
    negative_weight: null
    sampling_num_process: 1
    fix_sampling_seeds: True
    ignore_pos_items: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: 'Recall(k=20)'
    monitor_mode: 'max'